# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fgvsearch',
                'doc_host': 'https://thigm85.github.io',
                'git_url': 'https://github.com/thigm85/fgvsearch',
                'lib_path': 'fgvsearch'},
  'syms': {'fgvsearch.core': {'fgvsearch.core.foo': ('core.html#foo', 'fgvsearch/core.py')}}}